FROM node:8
ARG proxy

WORKDIR /matchid
COPY package.json .
VOLUME /matchid/src
VOLUME /matchid/build
VOLUME /matchid/config
VOLUME /matchid/matchIdConfig
VOLUME /matchid/dist

# cache package.json and node_modules to speed up builds
RUN npm config `echo $proxy | sed 's/^$/delete proxy/;s/\(\S\S*\)/set proxy \1/'`
RUN npm install

#COPY . . 

EXPOSE 8080
CMD ["npm","run","build"]
